[build]
  command = "npx convex deploy --cmd 'pnpm build:netlify'"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  # Build metadata for update detection
  BUILD_ID = "${COMMIT_REF}.${DEPLOY_ID}"
  GIT_SHA = "${COMMIT_REF}"
  VITE_CHANNEL = "prod"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure correct caching for update detection
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/build.json"
  [headers.values]
    Cache-Control = "no-store"

# Context-specific builds
[context.production]
  command = "npx convex deploy --cmd 'pnpm build:netlify' && node scripts/post-deploy.js"

[context.deploy-preview]
  command = "npx convex deploy --cmd 'pnpm build:netlify'"
  environment = { VITE_CHANNEL = "staging" }
